export const GET_INVOICES = "GET_INVOICES";
export const GET_INVOICES_SUCCESS = "GET_INVOICES_SUCCESS";
export const GET_INVOICES_FAILURE = "GET_INVOICES_FAILURE";

export const NEW_INVOICE = "NEW_INVOICE"
export const NEW_INVOICE_SUCCESS = "NEW_INVOICE_SUCCESS"
export const NEW_INVOICE_FAILURE = "NEW_INVOICE_FAILURE"

export const EDIT_INVOICE = "EDIT_INVOICE"
export const EDIT_INVOICE_SUCCESS = "EDIT_INVOICE_SUCCESS"
export const EDIT_INVOICE_FAILURE = "EDIT_INVOICE_FAILURE"

export const DELETE_INVOICE = "DELETE_INVOICE"
export const DELETE_INVOICE_SUCCESS = "DELETE_INVOICE_SUCCESS"
export const DELETE_INVOICE_FAILURE = "DELETE_INVOICE_FAILURE"

export const GET_ARTICLES = "GET_ARTICLES"
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS"
export const GET_ARTICLES_FAILURE = "GET_ARTICLES_FAILURE"

export const DELETE_ARTICLES = "DELETE_ARTICLES"
export const DELETE_ARTICLES_SUCCESS = "DELETE_ARTICLES_SUCCESS"
export const DELETE_ARTICLES_FAILURE = "DELETE_ARTICLES_FAILURE"

export const SEARCHING_INVOICE = "SEARCHING_INVOICE"
export const SEARCHING_INVOICE_SUCCESS = "SEARCHING_INVOICE_SUCCESS"
export const SEARCHING_INVOICE_FAILURE = "SEARCHING_INVOICE_FAILURE"

export const SEARCHING_ITEMS = "SEARCHING_ITEMS"
export const SEARCHING_ITEMS_SUCCESS = "SEARCHING_ITEMS_SUCCESS"
export const SEARCHING_ITEMS_FAILURE = "SEARCHING_ITEMS_FAILURE"

export const CLEAN_ALERT = "CLEAN_ALERT"