export const DOWNLOADING_DATA = "DOWNLOADING_DATA"
export const DOWNLOADING_DATA_FAILURE = "DOWNLOADING_DATA_FAILURE"
export const DOWNLOADING_DATA_SUCCESS = "DOWNLOADING_DATA_SUCCESS"

export const NEW_ACCOUNT = "NEW_ACCOUNT"
export const NEW_ACCOUNT_SUCCESS = "NEW_ACCOUNT_SUCCESS"
export const NEW_ACCOUNT_FAILURE = "NEW_ACCOUNT_FAILURE"

export const LOGIN_ACCOUNT = "LOGIN_ACCOUNT"
export const LOGIN_ACCOUNT_SUCCESS = "LOGIN_ACCOUNT_SUCCESS"
export const LOGIN_ACCOUNT_FAILURE = "LOGIN_ACCOUNT_FAILURE"

export const CHECK_TOKEN = "CHECK_TOKEN"
export const CHECK_TOKEN_SUCCESS = "CHECK_TOKEN_SUCCESS"
export const CHECK_TOKEN_FAILURE = "CHECK_TOKEN_FAILURE"

export const LOG_OUT = "LOG_OUT"

export const CLEAN_ALERT = "CLEAN_ALERT"

